In [6]:
import numpy as np #numpy 라이브러리 사용

In [7]:
data = [1, 2, 3, 4, 5] #리스트 생성

In [8]:
arr = np.array(data) #numpy 라이브러리를 통해서 우리가 흔히 알 수 있는 행렬 형태로 바꿔준다.

In [10]:
arr.shape #데이터가 몇 개인지 알려준다.

(5,)

In [11]:
arr.dtype #해당 데이터가 어떤 데이터 타입인지 확인한다.

dtype('int64')

In [14]:
np.zeros((9, 2)) #0만 가지고 있는 9행 2열의 행렬을 생성한다.

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.zeros((5, 5)) #0만 가지고 있는 5행 5열의 행렬을 생성한다.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.arange(20) #0부터 19까지 1씩 증가하는 20개의 수열을 생성한다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
np.arange(10) #0부터 9까지 1씩 증가하는 10개의 수열을 생성한다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])